-- DELETE FROM workout_sets;
-- DELETE FROM workout_sessions;
-- DELETE FROM exercise_muscle_groups;
-- DELETE FROM exercises;

-- CHEST
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Bench Press', 'Classic chest builder using a barbell on a flat bench.', 'https://www.youtube.com/watch?v=vcBig73ojpE', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Bench-press-form.jpg', 'CHEST', 'INTERMEDIATE', 'Barbell');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Push-Ups', 'Bodyweight exercise for chest and triceps.', 'https://www.youtube.com/watch?v=IODxDxX7oi4', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Push-up-form.jpg', 'CHEST', 'BEGINNER', 'Bodyweight');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Incline Dumbbell Press', 'Targets the upper chest using dumbbells and an inclined bench.', 'https://www.youtube.com/watch?v=8iPEnn-ltC8', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Incline-dumbbell-press-form.jpg', 'CHEST', 'INTERMEDIATE', 'Dumbbells');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Chest Flys', 'Isolation exercise for chest stretch and contraction.', 'https://www.youtube.com/watch?v=eGjt4lk6g34', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Dumbbell-fly-form.jpg', 'CHEST', 'INTERMEDIATE', 'Dumbbells');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Cable Crossover', 'Constant tension chest exercise using cables.', 'https://www.youtube.com/watch?v=taI4XduLpTk', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Cable-crossover-form.jpg', 'CHEST', 'INTERMEDIATE', 'Cable Machine');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Chest Dips', 'Targets lower chest and triceps.', 'https://www.youtube.com/watch?v=2z8JmcrW-As', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Chest-dips.jpg', 'CHEST', 'INTERMEDIATE', 'Dip Station');

-- BACK
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Pull-Ups', 'Superior back and bicep builder using bodyweight.', 'https://www.youtube.com/watch?v=eGo4IYlbE5g', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Pull-up-form.jpg', 'BACK', 'ADVANCED', 'Pull-up Bar');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Bent Over Row', 'Powerful back thickness exercise using a barbell.', 'https://www.youtube.com/watch?v=9efgcAjQe7E', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Barbell-row-form.jpg', 'BACK', 'INTERMEDIATE', 'Barbell');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Lat Pulldown', 'Wide grip pulldown to target the latissimus dorsi.', 'https://www.youtube.com/watch?v=0oeIB6wi3es', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Lat-pulldown-form.jpg', 'BACK', 'BEGINNER', 'Cable Machine');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Deadlift', 'Total posterior chain powerhouse.', 'https://www.youtube.com/watch?v=Xs78Z496v90', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Deadlift-form.jpg', 'BACK', 'ADVANCED', 'Barbell');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('T-Bar Row', 'Targets the middle back for thickness.', 'https://www.youtube.com/watch?v=j3Igk5nyZE4', 'https://www.strengthlog.com/wp-content/uploads/2020/03/T-bar-row.jpg', 'BACK', 'INTERMEDIATE', 'T-Bar Machine');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Face Pulls', 'Great for rear delts and upper back health.', 'https://www.youtube.com/watch?v=rep-qVOkqgk', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Face-pull.jpg', 'BACK', 'BEGINNER', 'Cable Machine');

-- LEGS
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Back Squat', 'The king of leg exercises, targeting quads and glutes.', 'https://www.youtube.com/watch?v=gcNh17Ckjgg', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Squat-form.jpg', 'LEGS', 'ADVANCED', 'Barbell');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Leg Press', 'Machine exercise to push heavy weight for quad growth.', 'https://www.youtube.com/watch?v=IZxyjW7MPJQ', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Leg-press-form.jpg', 'LEGS', 'BEGINNER', 'Leg Press Machine');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Romanian Deadlift', 'Targets hamstrings and glutes with a hip hinge.', 'https://www.youtube.com/watch?v=JCXUYuzwvgw', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Romanian-deadlift-form.jpg', 'LEGS', 'INTERMEDIATE', 'Barbell');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Leg Extensions', 'Isolation exercise for the quadriceps.', 'https://www.youtube.com/watch?v=YyvSfVLYQyc', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Leg-extension.jpg', 'LEGS', 'BEGINNER', 'Leg Extension Machine');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Leg Curls', 'Isolation exercise for the hamstrings.', 'https://www.youtube.com/watch?v=1Tq3QdYUuHs', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Leg-curl.jpg', 'LEGS', 'BEGINNER', 'Leg Curl Machine');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Calf Raises', 'Targets the gastrocnemius and soleus.', 'https://www.youtube.com/watch?v=-M4-G8p8fmc', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Calf-raise.jpg', 'LEGS', 'BEGINNER', 'Calf Machine');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Lunges', 'Unilateral leg exercise for quads and balance.', 'https://www.youtube.com/watch?v=QOVaHwm-Q6U', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Lunge.jpg', 'LEGS', 'BEGINNER', 'Bodyweight');

-- SHOULDERS
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Overhead Press', 'Compound movement for shoulder strength.', 'https://www.youtube.com/watch?v=hz_fT_vTf8I', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Overhead-press.jpg', 'SHOULDERS', 'INTERMEDIATE', 'Barbell');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Lateral Raises', 'Isolation for the side delts.', 'https://www.youtube.com/watch?v=3VcKaXpzqRo', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Lateral-raise.jpg', 'SHOULDERS', 'BEGINNER', 'Dumbbells');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Arnold Press', 'Twisting shoulder press for full shoulder development.', 'https://www.youtube.com/watch?v=6mcTMTm8f1U', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Arnold-press.jpg', 'SHOULDERS', 'INTERMEDIATE', 'Dumbbells');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Front Raises', 'Targets the anterior deltoids.', 'https://www.youtube.com/watch?v=-t7fuZ0KhDA', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Front-raise.jpg', 'SHOULDERS', 'BEGINNER', 'Dumbbells');

-- ARMS
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Bicep Curls', 'Standard bicep builder.', 'https://www.youtube.com/watch?v=uO_CNYidT80', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Bicep-curl-form.jpg', 'ARMS', 'BEGINNER', 'Barbell');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Hammer Curls', 'Targets the brachialis and forearms.', 'https://www.youtube.com/watch?v=7jqi2qWAUzQ', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Hammer-curl.jpg', 'ARMS', 'BEGINNER', 'Dumbbells');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Tricep Pushdown', 'Effective cable move for tricep isolation.', 'https://www.youtube.com/watch?v=2-LAMcpzODU', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Tricep-pushdown-form.jpg', 'ARMS', 'BEGINNER', 'Cable Machine');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Skull Crushers', 'Lying tricep extension for maximum stretch.', 'https://www.youtube.com/watch?v=d_KZx7p_djI', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Skull-crusher.jpg', 'ARMS', 'INTERMEDIATE', 'EZ Bar');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Preacher Curls', 'Isolation for the peak of the bicep.', 'https://www.youtube.com/watch?v=fIWP-FRFNU0', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Preacher-curl.jpg', 'ARMS', 'INTERMEDIATE', 'Preacher Bench');

-- CORE
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Planks', 'Core stability and isometric strength.', 'https://www.youtube.com/watch?v=pSHjTRCQxIw', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Plank.jpg', 'CORE', 'BEGINNER', 'Bodyweight');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Leg Raises', 'Excellent for lower abdominal development.', 'https://www.youtube.com/watch?v=l4kQd9eWclE', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Leg-raise.jpg', 'CORE', 'INTERMEDIATE', 'Bodyweight');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Russian Twists', 'Targets the obliques and rotation.', 'https://www.youtube.com/watch?v=wnwNoW8Wst8', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Russian-twist.jpg', 'CORE', 'BEGINNER', 'Bodyweight');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Crunches', 'Basic upper abdominal movement.', 'https://www.youtube.com/watch?v=Xyd_fa5zoEU', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Crunch.jpg', 'CORE', 'BEGINNER', 'Bodyweight');

-- CARDIO
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Running', 'Steady-state cardio on a treadmill or outdoors.', 'https://www.youtube.com/watch?v=_kGESn8IpU0', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Running.jpg', 'CARDIO', 'BEGINNER', 'Treadmill');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Cycling', 'Low impact cardiovascular exercise.', 'https://www.youtube.com/watch?v=4yS6W9C6m3I', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Cycling.jpg', 'CARDIO', 'BEGINNER', 'Stationary Bike');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Jump Rope', 'High intensity cardio and coordination.', 'https://www.youtube.com/watch?v=u3zgHI8Qnq8', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Jump-rope.jpg', 'CARDIO', 'INTERMEDIATE', 'Jump Rope');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Burpees', 'Full body explosive cardio move.', 'https://www.youtube.com/watch?v=dZgVxmf6jkA', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Burpee.jpg', 'CARDIO', 'ADVANCED', 'Bodyweight');
INSERT INTO exercises (name, description, video_url, form_image_url, body_part, difficulty, equipment) VALUES ('Row Machine', 'Full body cardio and back engagement.', 'https://www.youtube.com/watch?v=H0IDdq3H96M', 'https://www.strengthlog.com/wp-content/uploads/2020/03/Row-machine.jpg', 'CARDIO', 'INTERMEDIATE', 'Rowing Machine');

-- Muscle Groups Mapping
INSERT INTO exercise_muscle_groups (exercise_id, muscle_group) SELECT id, 'Chest' FROM exercises WHERE name IN ('Bench Press', 'Push-Ups', 'Incline Dumbbell Press', 'Chest Flys', 'Cable Crossover', 'Chest Dips');
INSERT INTO exercise_muscle_groups (exercise_id, muscle_group) SELECT id, 'Back' FROM exercises WHERE name IN ('Bent Over Row', 'Lat Pulldown', 'Deadlift', 'Pull-Ups', 'T-Bar Row', 'Face Pulls');
INSERT INTO exercise_muscle_groups (exercise_id, muscle_group) SELECT id, 'Biceps' FROM exercises WHERE name IN ('Pull-Ups', 'Bicep Curls', 'Hammer Curls', 'Preacher Curls');
INSERT INTO exercise_muscle_groups (exercise_id, muscle_group) SELECT id, 'Triceps' FROM exercises WHERE name IN ('Tricep Pushdown', 'Skull Crushers', 'Bench Press', 'Chest Dips');
INSERT INTO exercise_muscle_groups (exercise_id, muscle_group) SELECT id, 'Quads' FROM exercises WHERE name IN ('Back Squat', 'Leg Press', 'Leg Extensions', 'Lunges');
INSERT INTO exercise_muscle_groups (exercise_id, muscle_group) SELECT id, 'Hamstrings' FROM exercises WHERE name IN ('Back Squat', 'Romanian Deadlift', 'Leg Curls');
INSERT INTO exercise_muscle_groups (exercise_id, muscle_group) SELECT id, 'Calves' FROM exercises WHERE name IN ('Calf Raises');
INSERT INTO exercise_muscle_groups (exercise_id, muscle_group) SELECT id, 'Shoulders' FROM exercises WHERE name IN ('Overhead Press', 'Lateral Raises', 'Arnold Press', 'Front Raises', 'Face Pulls');
INSERT INTO exercise_muscle_groups (exercise_id, muscle_group) SELECT id, 'Core' FROM exercises WHERE name IN ('Planks', 'Leg Raises', 'Russian Twists', 'Crunches');
INSERT INTO exercise_muscle_groups (exercise_id, muscle_group) SELECT id, 'Full Body' FROM exercises WHERE name IN ('Deadlift', 'Burpees', 'Row Machine');

